blank_issues_enabled: true
contact_links:
  - name: Question / discussion
    url: https://github.com/r14dd/patent/discussions
    about: For usage questions, ideas, and show-and-tell, please use Discussions.
